config/routes.rb
Rails.application.routes.draw do
  resources :meetings

  devise_for :users
  
  
  
  get '/meet', to: 'meetings#all_users_meetings'

  root to: 'meetings#show_calendar'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base

	acts_as_schedulable :schedule
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :meetings

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @meetings = current_user.meetings
  end
  
  def all_users_meetings
    @meetings = Meeting.all
  end

  def show
  end

  def new
    @meeting = Meeting.new
  end

  def edit
  end


  def show_calendar
    
    @meetings = current_user.meetings
    @finalMeetings = Array.new

    @meetings.each do |s|
      @finalMeetings.push(s)  
    
      if s.rule == "weekly"
        interval = s.interval
        count = 7
        while interval != 0
          newDate = s.dup
          newDate.start_time += count.days
          count+=7
          @finalMeetings.push(newDate)
          interval -= 1
        end
      end
      if s.rule == "daily"
        interval = s.interval
        count = 1
        while interval != 0
          newDate = s.dup
          newDate.start_time += count.days
          count+=1
          @finalMeetings.push(newDate)
          interval -= 1
        end
      end
      if s.rule == "monthly"
        interval = s.interval
        count=30
        while interval != 0
          newDate = s.dup
          newDate.start_time += count.days
          count+=30
          @finalMeetings.push(newDate)
          interval -= 1
        end
      end
      if s.rule == "annually"
        interval = s.interval
        count=365
        while interval != 0
          newDate = s.dup
          newDate.start_time += count.days
          count+=365
          @finalMeetings.push(newDate)
          interval -= 1
        end
      end
    end

  end

  def create
    @meeting = current_user.meetings.create(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }      
      else
        format.html { render :new }        
      end
    end
  end

  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }      
      else
        format.html { render :edit }
      end
    end
  end

 def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
    end
  end

  private

  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:name, :start_time, :rule, :interval)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    
  </small>
  <nav>
    <ul>
     
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "calendar app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "New Event",    new_meeting_path %></li>
          <li><%= link_to "All Users Events",    '/meet' %></li>
          <li><%= link_to "Your Events",    '/meetings' %></li>
          <li><%= link_to "Edit Profile",    edit_user_registration_path %></li>
          <!-- <li><%= link_to "Exit",    destroy_user_session_path %></li> -->
          <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </li>
        <% else %>
            
        <% end %>
        </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
      
    </div>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= f.label :rule%><br>
    <%= f.select(:rule, ["daily", "weekly", "monthly", "annually"]) %>
    
  </div>

  <div class="field">
    <%= f.label :interval%><br>
    <%= f.text_field :interval%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/all_users_meetings.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @meetings.each do |meeting| %>
      <tr class="spaceUnder">

        <td><%= meeting.name %></td>
        
        <td><%= meeting.start_time %></td>
  
        <% current_user.meetings.each do |meet|%>
			
					<% if meeting == meet %>
		 			  
		 			  <td><button><%= link_to 'Show', meeting %></button></td>
        
       			<td><button ><%= link_to 'Edit', edit_meeting_path(meeting) %></button></td>
        
       			<td><button ><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
     
					<% end %>

				<% end %>

      </tr>

    <% end %>
  </tbody>
</table>

<br>
<button><%= link_to 'Back', root_path %></button>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form' %>

<button><%= link_to 'Show', @meeting %></button> 
<button><%= link_to 'Back', root_path %></button>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @meetings.each do |meeting| %>
      <tr class="spaceUnder">
        <td><%= meeting.name %></td>
        
        <td><%= meeting.start_time %></td>
        
        <td><button><%= link_to 'Show', meeting %></button></td>
        
        <td><button ><%= link_to 'Edit', edit_meeting_path(meeting) %></button></td>
        
        <td><button ><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

<button><%= link_to 'New Meeting', new_meeting_path %></button><br></br>
<button><%= link_to 'Back', root_path %></button>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form' %>

<button><%= link_to 'Back', root_path %></button>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meeting.name %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @meeting.start_time %>
</p>

<button><%= link_to 'Edit', edit_meeting_path(@meeting) %></button> 
<button><%= link_to 'Back', meetings_path %></button>

app/views/meetings/show_calendar.html.erb
<%= month_calendar events: @finalMeetings do |date, meetings| %>
  <%= date %>

  <% meetings.each do |meeting| %>
    <div class = "calendarElement">
      <%= link_to meeting.name%><br></br>
    </div>
  <% end %>
<% end %>
<!-- , edit_meeting_path(meeting)  -->

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <br></br>
  <div class="calendar-heading">
    <button><%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %></button>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <button><%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %></button>
  </div>
  <br></br>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>